### ISSUE TITLE
Bug report: Restore Inventory button not showing

### ISSUE THREAD

**Issue by NameIsCam** [TechnicallyCoded/Inventory-Rollback-Plus#30] opened 2021-07-20 21:14 UTC
### Bug description:
When I open the GUI menu to restore a player's inventory, the button to force a player's inventory to the backup does not appear (a nether star I believe).

### Server details:
 - Paper 1.17.1-R0.1-SNAPSHOT
 - v1.6.1

### How to reproduce:
N/A

### What was expected:
A button to force the player's inventory to the backup.

### Screenshots, logs & other:
N/A

#### **Additional info:**
I did check the config to see if it's something to set or activate but I didn't see anything. Sorry for taking away your time if this isn't a bug, and it's a configuration error on my part.

**Comment by TechnicallyCoded** [comment] 2021-07-20 21:59
Duplicate of #10

**Closed** 2021-07-25 14:14 UTC
Labels: not-a-bug, support
