### ISSUE TITLE
Bug report: [Plugin records fake deaths from falling]

### ISSUE THREAD

**Issue by GitGoppy** [TechnicallyCoded/Inventory-Rollback-Plus#21] opened 2021-05-29 10:01 UTC
### Bug description:
*A clear and concise description of what the bug is.*
When a player that has highly enhcanted netherite armor and jumps of a cliff, doesn't die but inventoryrollback records the player's inventory as if they died due to fall damage.

### Server details:
 - Server type & version: *Not relevant*
 - InventoryRollbackPlus version: 1.6.0

### How to reproduce:
*Steps to reproduce the behavior. If not applicable just replace this line with N/A*
Get prot 4 and feather falling 4 on netherite armor
and jump from height of 154 blocks to the ground (154 blocks between ground and jump point)
### What was expected:
The deaths tab in inventory rollback records a death inventory with the time when the person touched the ground
and with reason FALLING

### Screenshots, logs & other:
Not necessary, really easy to test

#### **Additional info:**
Inventoryrollback probably doesn't take armor and enchants into account when calculating whether a player died from a fall.
Pls fix.

**Comment by TechnicallyCoded** [comment] 2021-06-01 10:23
It's unrelated to armor and enchants but rather something we call finalDamage. This value can be changed by armor, enchants, potion effects like resistance, plugins, and other things I am not thinking of. However, this was already addressed in the current release on spigot. The only change I could make is the priority on which the plugin is listening. This would however only have an effect if a plugin is reducing damage on a higher priority than normal. (existing priorities are lowest, low, normal, high, highest, monitor)

I have changed the priority to the highest possible (monitor) since the plugin makes no changes to the end result and therefore should have probably been using this priority anyway but if this is purely an armor & enchants issue it will not change anything.

Snippet from the spigot/bukkit javadocs about finalDamage:
```
public final double getFinalDamage()
Gets the amount of damage caused by the event after all damage reduction is applied.
```

**Comment by TechnicallyCoded** [comment] 2021-06-23 10:59
This issue will be closed in a few days if no further information is provided as to how to reproduce this. I have tried re-creating this with feather-falling armor. It works as intended.

**Closed** 2021-07-07 14:27 UTC
Labels: bug
