### ISSUE TITLE
Bug report: Inventory not backing up when bundle is in inventory

### ISSUE THREAD

**Issue by RainbowTea** [TechnicallyCoded/Inventory-Rollback-Plus#28] opened 2021-07-19 00:46 UTC
### Bug description:
When a filled bundle is in the inventory it will not backup the inventory at all.

### Server details:
 - Server type & version: *Paper version git-Paper-109 (MC: 1.17.1)*
 - InventoryRollbackPlus version: *  Running InventoryRollbackPlus v1.6.1*

### How to reproduce:
- Delete old jar & folder of the plugin
- Reinstalled new jar
- Boot up server
- Placed bundle in my inventory + random items inside the bundle.
- Logged out then back in
- /irp username to restore inventory selected the quit/bed icon section for the backup.
- Received errors below. 

This only happens when there is a bundle. Otherwise it works just fine.
### What was expected:
I expected it to save the bundle and its items.

### Screenshots, logs & other:
https://pastebin.com/3N0JUchj
![image](https://user-images.githubusercontent.com/45947107/126087790-603e89ab-0cf8-415c-964f-eaa01e7bee09.png)

#### **Additional info:**
It works otherwise, but if there is a bundle the inventory will not save.

**Comment by TechnicallyCoded** [comment] 2021-07-21 12:27
Hi, I spent hours trying to figure out why it wasn't saving the items correctly... then realized that the reason behind your errors is that spigot itself does not actually support bundles. This means that there is no way that I can actually fix this. Once spigot supports bundles in 1.18, then you will be able to have them save. A workaround that I can use for the moment is to skip saving the bundles in version 1.17.x in order to still allow saving of the rest of the inventory.

**Comment by RainbowTea** [comment] 2021-07-22 08:02
> Hi, I spent hours trying to figure out why it wasn't saving the items correctly... then realized that the reason behind your errors is that spigot itself does not actually support bundles. This means that there is no way that I can actually fix this. Once spigot supports bundles in 1.18, then you will be able to have them save. A workaround that I can use for the moment is to skip saving the bundles in version 1.17.x in order to still allow saving of the rest of the inventory.

Thats odd because i found another spigot plugin that saves and restores bundles  with items in it too just fine (i however prefer your plugin as it has more features).

**Comment by TechnicallyCoded** [comment] 2021-07-22 09:15
> 
> 
> > Hi, I spent hours trying to figure out why it wasn't saving the items correctly... then realized that the reason behind your errors is that spigot itself does not actually support bundles. This means that there is no way that I can actually fix this. Once spigot supports bundles in 1.18, then you will be able to have them save. A workaround that I can use for the moment is to skip saving the bundles in version 1.17.x in order to still allow saving of the rest of the inventory.
> 
> Thats odd because i found another spigot plugin that saves and restores bundles with items in it too just fine (i however prefer your plugin as it has more features).

They probably use a custom saving format. This plugin uses the built-in BukkitObjectOutputStream which makes the plugin ... usually... more future proof to changes made by bukkit/spigot. 
That is my guess for how that other plugin works. However, I can assure you that I looked through the spigot code and issues and the error we are dealing with is caused by an explicit disabling of a method.

**Comment by TechnicallyCoded** [comment] 2021-07-22 09:23
For the moment I added a workaround to still allow saving of the rest of the inventory. [https://github.com/TechnicallyCoded/Inventory-Rollback-Plus/commit/22bfc1d53c31ea0e4553e0eb8c9ea02229739106](https://github.com/TechnicallyCoded/Inventory-Rollback-Plus/commit/22bfc1d53c31ea0e4553e0eb8c9ea02229739106)

And this is the related code if you are technically inclined, this code section is our problem. [https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/inventory/CraftMetaBundle.java#35-37,46-47](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/inventory/CraftMetaBundle.java#35-37,46-47)

**Comment by TechnicallyCoded** [comment] 2021-08-03 18:08
I reported this behavior to spigot nevertheless and it seems to have been of use. The issue was marked as resolved, so we might have bundle saving/restoring support in 1.17.1.

https://hub.spigotmc.org/jira/browse/SPIGOT-6666

Note that I have not tested this yet, you could make sure you are up to date and see if this still happens :)

**Comment by TechnicallyCoded** [comment] 2021-08-12 13:01
As of Paper build \#126 (commit [9b828509cd6d89a2cc4b023631d5dd4dcfc22e2d](https://github.com/PaperMC/Paper/commit/9b828509cd6d89a2cc4b023631d5dd4dcfc22e2d)) and spigot commit [82f0955b3bf72242919101fa2cbfaae7d663b7c3](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/82f0955b3bf72242919101fa2cbfaae7d663b7c3), this issue seems to be resolved.

**Closed** 2021-09-20 17:14 UTC
Labels: bug, fixed, #not-my-fault
