### ISSUE TITLE
Can you add a function for Auto Force Backup?

### ISSUE THREAD

**Issue by SaranWSM** [TechnicallyCoded/Inventory-Rollback-Plus#65] opened 2022-01-19 03:17 UTC
Can you add a function for Auto Force Backup?

**Comment by TechnicallyCoded** [comment] 2022-01-19 10:01
This is a duplicate of #11 , please comment there if there anything you want to add, or even just to show your support for the feature request! :D

**Closed by TechnicallyCoded** 2022-01-19 10:01 UTC
Labels: feature-request

**Comment by SaranWSM** [comment] 2022-01-20 04:54
i need Auto Force Backup.

**Comment by TechnicallyCoded** [comment] 2022-01-20 09:37
Go to issue #11
