### ISSUE TITLE
How do the plugin handle player death

### ISSUE THREAD

**Issue by broken1arrow** [TechnicallyCoded/Inventory-Rollback-Plus#162] opened 2024-08-07 13:42 UTC
I have notes some players have problems when using Inventory-Rollback-Plus and death-chest. I can't say what the reason is behind it clear the inventory. But I did try to change the listener priory, but your plugin seams to lessen at a higher level than I set.  

So how do this plugin handle player death, so I could adjust the logic?

**Comment by MrKioZ** [comment] 2024-08-11 06:55
Yea i am have the same issue with me and i am using Angel Chest plugin in combination with this plugin could be the cause of issue that angel chest handles the event before this plugin i dont know

**Comment by TechnicallyCoded** [comment] 2024-08-12 16:35
@broken1arrow
https://github.com/TechnicallyCoded/Inventory-Rollback-Plus/issues/162#issue-2453522692

During the death event you have the ability to clear the drops list without clearing the player's inventory. 

`List#clear()` on the following should work:
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/EntityDeathEvent.html#getDrops()

**Comment by TechnicallyCoded** [comment] 2024-08-12 17:25
Please bring the author into this conversation, I can't bring back deleted data. Just not possible.

**Comment by TylorTurner** [comment] 2024-08-17 07:36
Any solution yet with angelchest? I currently do not have any deaths either.

**Comment by WaxenSs** [comment] 2024-08-18 08:25
@TylorTurner For the moment, no. The developers are working on it together, so let's give them some time :)

**Comment by TechnicallyCoded** [comment] 2024-12-15 17:55
Closing this as resolved. AngelChest has a config option for this now, plus I have made some changes to forcibly hook into the death events before AngelChests, DeadChest, etc get the chance to change anything.

**Closed** 2024-12-15 17:55 UTC
Labels: Medium Priority, resolved-in-dev-branch
